name: Test install instructions

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  # Test installation.
  test-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Kubernetes tools
        uses: stefanprodan/kube-tools@v1
        with:
          kubectl: 1.18.2
          kustomize: 3.5.5
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.3.0
        with:
          minikube version: 'v1.15.1'
          kubernetes version: 'v1.17.11'
      - run: |
          TAG=main
          kustomize build github.com/iter8-tools/iter8-kfserving/install?ref=$TAG | kubectl apply -f -
          kubectl wait crd -l creator=iter8 --for condition=established --timeout=120s
          kustomize build github.com/iter8-tools/iter8-kfserving/install/iter8-metrics?ref=$TAG | kubectl apply -f -

          TAG=main
          kustomize build github.com/iter8-tools/iter8-kfserving/install/monitoring/prometheus-operator?ref=$TAG | kubectl apply -f -
          kubectl wait crd -l creator=iter8 --for condition=established --timeout=120s
          kustomize build github.com/iter8-tools/iter8-kfserving/install/monitoring/prometheus?ref=$TAG | kubectl apply -f -

          kubectl wait --for condition=ready --timeout=300s pods --all -n iter8-system
          kubectl wait --for condition=ready --timeout=300s pods --all -n kfserving-monitoring
